name: aoc2022
channels:
  - defaults
dependencies:
  - django=4.1
  - markdown=3.3
  - matplotlib=3.5
  - numpy=1.23
  - pandas=1.5
  - pip=22.2
  - pylint=2.14
  - python=3.10
  - pip:
    - djangorestframework=3.14
