name: aoc2022
channels:
  - defaults
dependencies:
  - coverage 6.3
  - django=4.1
  - jupyter=1.0
  - markdown=3.3
  - matplotlib=3.5
  - numpy=1.23
  - pandas=1.5
  - pip=22.2
  - pylint=2.14
  - pytest=7.1
  - python=3.10
  - pip:
    - djangorestframework==3.14
